### ISSUE TITLE
[Feature]: Make money scaling implicit

### ISSUE THREAD

**Issue by kaomoneus** [kaomoneus/OpenTTD#10]
### Version of OpenTTD this feature is to be implemented.

12.1.slowpace-1.2

### Description

Currently we multiply max loan amount, vehicle costs and some other costs on *pace factor*. Main motivation is to keep payback periods unchanged comparing to legacy modes.

1. Introduce *virtual* currency on top of chosen currency with rate *1/<pace_factor>*.
2. Add support of prices with fractional numbers. 

All together it will allow to keep max loan, and costs unchanged comparing to legacy. At same time fares per single trip will be reduced and for big *pace factor* will become less than 1. E.g. bus might earn $0.54.

This approach supposed to be more intuitive for user experience.

### Implementation description

It seems that all stuff should be done in [`FormatGenericCurrency`](https://github.com/kaomoneus/OpenTTD/blob/76d463f768cf3b5c098706aaf9c3d44b28da18c4/src/strings.cpp#L475).

In fact we don't even need a virtual currency. Just add support for decimal point and divide on *pace factor*

**Comment by kaomoneus** [comment]
Just pushed implementation. Still wait before merge for may be some feedback.

Here's a screenshot (year pace = 1 hour):
![Screen Shot 2022-01-06 at 7 45 32 PM](https://user-images.githubusercontent.com/857042/148410251-962c4055-3573-4f84-9ef0-17f22042eb27.png)

**Comment by James103** [comment]
Would it be possible to
1. Make sure that currency amounts show only 0, 2, or 3 digits. It is unusual for there to only be one digit after the decimal in a monetary amount.
2. Take into account the exchange rate of the current currency with respect to the GBP when deciding how many digits after the decimal to show. In other words, even if the game pace factor is 100:1, if you use JPY, no decimals should be shown because the exchange rate (220:1) exceeds the game pace factor (100:1).

**Comment by kaomoneus** [comment]
Ok, that makes sense

**Comment by Ufiby** [comment]
How did you calculate finances with a growth factor? If 1 annual pace is equal to 1 hour. 1 hour means that the coefficient is multiplied by 4. There is a possibility that 1 annual pace will be 2.5 hours. Thus, the coefficient is multiplied by 10. To receive payments from the profit, the price is divided by 10. Is this an opportunity ?

**Comment by kaomoneus** [comment]
Implemented in 8fb25e1f601
